//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReelStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Reel_Bom
    {
        public int ID { get; set; }
        public string Reel_Size { get; set; }
        public Nullable<double> Drum_High { get; set; }
        public Nullable<double> Drum_Length { get; set; }
        public string Size { get; set; }
        public string Q_Unit { get; set; }
        public Nullable<double> Thickness { get; set; }
        public Nullable<double> Reel_Weight { get; set; }
        public Nullable<double> Lag_Reel { get; set; }
        public string Status { get; set; }
    }
}
