//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReelStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Member
    {
        public int Mem_ID { get; set; }
        public string Mem_Name { get; set; }
        public string Mem_User { get; set; }
        public string Mem_Pass { get; set; }
        public string Mem_Des { get; set; }
        public string Mem_Status { get; set; }
        public string Create_By { get; set; }
        public string Create_Date { get; set; }
        public string Update_Date { get; set; }
        public string Code_Mem { get; set; }
        public string Mem_authorization1 { get; set; }
        public string Mem_authorization2 { get; set; }
        public string Mem_authorization3 { get; set; }
        public string Mem_Function { get; set; }
    }
}
