//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReelStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Location
    {
        public int Lo_ID { get; set; }
        public string Lo_Name { get; set; }
        public string Lo_Des { get; set; }
        public string Lo_Code { get; set; }
        public string Lo_Status { get; set; }
        public string Lo_Check { get; set; }
    }
}
