//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReelStock.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Reel_StockEntities : DbContext
    {
        public Reel_StockEntities()
            : base("name=Reel_StockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Master_Reel_Bom> Master_Reel_Bom { get; set; }
        public virtual DbSet<Reel_TR_RegisReel> Reel_TR_RegisReel { get; set; }
        public virtual DbSet<Master_Member> Master_Member { get; set; }
        public virtual DbSet<Master_Location> Master_Location { get; set; }
        public virtual DbSet<Reel_TR_MoveLocation> Reel_TR_MoveLocation { get; set; }
    }
}
