//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReelStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reel_TR_RegisReel
    {
        public int ID { get; set; }
        public string Reel_Size { get; set; }
        public string Reel_Code { get; set; }
        public Nullable<System.DateTime> Reel_DateCreate { get; set; }
        public string Reel_Location { get; set; }
        public string Reel_Status { get; set; }
        public string Reel_User { get; set; }
    }
}
