//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReelStock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reel_TR_MoveLocation
    {
        public int ID { get; set; }
        public string Move_Barcode { get; set; }
        public string Move_User { get; set; }
        public Nullable<System.DateTime> Move_Date { get; set; }
        public string Move_Status { get; set; }
        public string Move_Location { get; set; }
        public string Move_Alert { get; set; }
        public string Move_Size { get; set; }
    }
}
